spring:
  application:
    name: ide-worker
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: ide
    password: ide
registry:
  type: zookeeper
  zookeeper:
    namespace: ide
    connect-string: 114.55.237.121:2181
    retry-policy:
      base-sleep-time: 60ms
      max-sleep: 300ms
      max-retries: 5
    session-timeout: 60s
    connection-timeout: 60s
    block-until-connected: 60s
    digest: ~
worker:
  # worker listener port
  listen-port: 1234
  # worker execute thread number to limit task instances in parallel
  exec-threads: 100
  batch-job-num: 3
  # worker heartbeat interval
  max-heartbeat-interval: 10s
  # worker host weight to dispatch tasks, default value 100
  host-weight: 100
  server-load-protection:
    # If set true, will open worker overload protection
    enabled: true
    # Worker max system cpu usage, when the worker's system cpu usage is smaller then this value, worker server can be dispatched tasks.
    max-system-cpu-usage-percentage-thresholds: 0.99
    # Worker max jvm cpu usage, when the worker's jvm cpu usage is smaller then this value, worker server can be dispatched tasks.
    max-jvm-cpu-usage-percentage-thresholds: 0.99
    # Worker max System memory usage , when the master's system memory usage is smaller then this value, master server can execute workflow.
    max-system-memory-usage-percentage-thresholds: 0.99
    # Worker max disk usage , when the worker's disk usage is smaller then this value, worker server can be dispatched tasks.
    max-disk-usage-percentage-thresholds: 0.99
  registry-disconnect-strategy:
    # The disconnect strategy: stop, waiting
    strategy: waiting
    # The max waiting time to reconnect to registry if you set the strategy to waiting
    max-waiting-time: 100s
  task-execute-threads-full-policy: REJECT
  datasource-password-aes-key: mySaltValue
yarn:
  application-state: http://namenode01-sit:8088/ws/v1/cluster/apps/%s/state
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: true
    defaults:
      enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
metrics:
  enabled: true

logging:
  config: classpath:logback-spring.xml
  file:
    path: /ide/log/ide-worker
logstash:
  destination: 114.55.237.121:4560
